// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tomato
List tomato(NumericMatrix coords, int num_neighb, double r, double threshold);
RcppExport SEXP _RSMLM_tomato(SEXP coordsSEXP, SEXP num_neighbSEXP, SEXP rSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type num_neighb(num_neighbSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(tomato(coords, num_neighb, r, threshold));
    return rcpp_result_gen;
END_RCPP
}
// tomatoDens
List tomatoDens(NumericMatrix coords, NumericVector density, double r, double threshold);
RcppExport SEXP _RSMLM_tomatoDens(SEXP coordsSEXP, SEXP densitySEXP, SEXP rSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type density(densitySEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(tomatoDens(coords, density, r, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSMLM_tomato", (DL_FUNC) &_RSMLM_tomato, 4},
    {"_RSMLM_tomatoDens", (DL_FUNC) &_RSMLM_tomatoDens, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSMLM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
